language: scala
jdk: oraclejdk11
scala: 2.11.11
script: "sbt ++$TRAVIS_SCALA_VERSION clean coverage test"
after_success: "sbt coverageReport coveralls"
notifications:
  email:
    recipients: guenter.hesse@hpi.de