language: scala
jdk:
  - openjdk8
scala:
    - 2.11.11
notifications:
  email:
    recipients:
      - guenter.hesse@hpi.de
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - sbt coveralls