language: scala
jdk:
  - openjdk8
scala:
    - 2.11.11
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test coverageAggregate coverage
after_success:
  - sbt coveralls
notifications:
  email:
    recipients:
      - guenter.hesse@hpi.de